### ISSUE TITLE
#1 Comments https://dev.impresso-project.ch/datalab/

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-datalab#10]
Wording and small enhancements
- [x] I cant seem to log out etc, expected the same dropdown menu as in web app
- [x] misses favicon
- [x] for consistency with Web app, adjust capitalisation: Get API Token, Browse Notebooks, 
- [x] impresso -> Impresso everywhere 
- [x] Give your media moni... -> Boost your Media Monitoring
- [x] We collected 100 Jupyter notebooks so far; orchestrated 2 collections of notebooks, developed by 10 authors. -> We created ?? Jupyter notebooks so far; curated ?? notebook collections with the help of ?? authors.
- [x] Three easy steps to enter the impresso way of doing research. -> Three easy steps to enter the Impresso Datalab.

Layout
- [x] To be discussed... 
- [x] A first time user needs to understand all the steps necessary. How about this for users which are not logged in: 
    - [x] Card 1 titled "Three easy steps to enter the Impresso Datalab": 
    Register your Impresso Account
    Consult our Terms of Use
    Generate your API key 

on the right of card 1:
- [x] Card 2: "Getting started". I like a lot the 3 lines of code to run the first query. But there is a bit of a disconnect to the "Initialise Impresso Client" linked below. It was not my first thought to click on it for further information... no good idea how to do better

below:

- [x] left Card 3: "Impresso Notebook Templates" 
- [x] right Card 4:  "Impresso Models to Enrich your Data"
"Work with your own data, the Impresso way." -> "Enrich your data, the Impresso way."

- [x] for a user that is logged in already we present 
- [x] "Initialize Impresso Client" = the getting started notebook? 

This in place of "Enter Impresso-py, the Python client for the impresso API" (?)
- [x] The 
- [ ]

**Comment by danieleguido** [comment]
The content is dummy for the moment, I generated most of it using helpful assistants 👯 
All notebooks are in src/content/notebooks, they are just pointer to already esisting notebooks. Feel free to change and adapt the "excerpt" there. Same things for `series` that are basically the box wrappers
