### ISSUE TITLE
[series] adapt content metadata

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-datalab#12]
The #10 issue feedback refers to this state:
<img width="1091" alt="Screenshot 2024-09-27 at 11 44 48" src="https://github.com/user-attachments/assets/833d1a0d-543b-40c3-8ac0-92df95cd54dc">

> Three easy steps to enter the impresso way of doing research. -> Three easy steps to enter the Impresso Datalab.

> Card 2: "Getting started". I like a lot the 3 lines of code to run the first query. But there is a bit of a disconnect to the "Initialise Impresso Client" linked below. It was not my first thought to click on it for further information... no good idea how to do better

We can put the updated notebooks in the enter-impresso serie

- left Card 3: "Impresso Notebook Templates"

- right Card 4: "Impresso Models to Enrich your Data"
"Work with your own data, the Impresso way." -> "Enrich your data, the Impresso way."

**Comment by simon-clematide** [comment]
Yes, we should adapt the the sequence and wording of the series.

**Comment by danieleguido** [comment]
series have been updated accordingly :)
