### ISSUE TITLE
change theme of the codesnippet in notebook preview

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-datalab#25]
E.g custom theme https://www.npmjs.com/package/@uiw/codemirror-themes
Requirements: code and running text should be balanced, like in github 

Current theme :
<img width="500" alt="Screenshot 2024-10-11 at 15 50 53" src="https://github.com/user-attachments/assets/1f9e28a6-20e3-45d6-9f4c-caa6a5192e9c">

e.g. on Github
<img width="500" alt="Screenshot 2024-10-11 at 15 51 49" src="https://github.com/user-attachments/assets/fb2cdfea-574b-4181-96be-df13a47c03f7">

**Comment by donsiamese** [comment]
![code snippet](https://github.com/user-attachments/assets/e9d15f2c-50ff-433b-8cb4-5ac695cc55d
A new style of the code snippet comp

**Comment by donsiamese** [comment]
A new style of the code snippet comp
![code snippet](https://github.com/user-attachments/assets/0b2aeadb-c5df-4ef1-96e8-d119ea3608f8)

**Comment by danieleguido** [comment]
merged in main
