### ISSUE TITLE
Datalab home page - various tweaks

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-datalab#28]
Top navigation
- [x] "Browse Ipynb Notebooks" -> Browse notebooks
- [x] The "Join us..." text blurb looks a bit cramped on a laptop monitor, is it possible to widen the margins a bit? See screenshot below
![image](https://github.com/user-attachments/assets/a1becfe4-b976-4d11-b594-ee355e27f8c0)

Getting started card: 
- [x] "impresso way of" -> "Impresso"
- [x] Step 2: "Consult our Terms of Use" -> "Accept our Terms of Use"
- [x] there is too much going on there: heading, subheading, text, steps, code, notebook. No good idea how to fix but it is overwhelming for me. One thought: remove the code snippet and make steps 1-3 more prominent?
- [x] notebook authors: only "Impresso Team", remove personal names

Explore and visualise your Data Card:
- [x] Add text below subheading: Notebook templates offer complementary views on your Impresso personal collections and external datasets beyond the capabilities of the Impresso Web App.
- [x] "Detect Entities" notebook needs to move to Card 3 "Enrich"

**Comment by danieleguido** [comment]
New excerpt for the "getting started"
~~Three easy steps to enter the impresso way of doing research.~~
Three simple steps to begin research with Impresso

**Comment by danieleguido** [comment]
We reduced the visual weight of the code snippets, making the notebooks card more prominent. What do you think?

**Comment by danieleguido** [comment]
Central series:
~~Explore and Visualise your Data.~~
Explore and Visualise your Impresso Data

**Comment by mduering** [comment]
> New excerpt for the "getting started" ~Three easy steps to enter the impresso way of doing research.~ Three simple steps to begin research with Impresso

Start your research with Impresso in three easy steps. (?)

**Comment by danieleguido** [comment]
Done :)
