### ISSUE TITLE
Tbd: Organisation of notebooks on Github and Readme.md should mirror Datalab home page

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-datalab#32]

**Comment by danieleguido** [comment]
We finally decided to keep the current hierarchy of folders in the impresso-datalab-notebooks repo. There, the notebook are grouped by category or author. On the Impresso Datalab website, they're grouped based on their "scope": *Getting Started*, *Explore and Visualise your Impresso data*, *Annotate your Documents with Impresso Models*.

**Comment by danieleguido** [comment]
I close this issue here, see https://github.com/impresso/impresso-datalab-notebooks/pull/14
