### ISSUE TITLE
wrong code example in "Annotate your Documents with Impresso Models" collection card

### ISSUE THREAD

**Issue by EmanuelaBoros** [impresso/impresso-datalab#43]
The example might confuse users - and it doesnt work.

```
# Use a pipeline as a high-level helper
!pip install transformers

from transformers import pipeline
pipe = pipeline("text2text-generation", model="impresso-project/nel-mgenre-multilingual")```
```

This is an old version of the code. I cannot find where this is set up in the code, thus I am adding here what code should it be:

```
!pip install transformers

from transformers import pipeline
nel_tokenizer = AutoTokenizer.from_pretrained("impresso-project/nel-mgenre-multilingual")

nel_pipeline = pipeline("generic-nel", model=NEL_MODEL_NAME, 
                        tokenizer=nel_tokenizer, 
                        trust_remote_code=True,
                        device='cpu')

```

**Comment by EmanuelaBoros** [comment]
It also says "Copy the code below in a blank jupyter notebook to get started". Not even sure if the example is really necessary, no?

**Comment by danieleguido** [comment]
I've corrected the code, but I see your point. The code in the first column serve as a generic snippet code for all the notebooks in the column. is there a similar code that serve this purposes and it is in common for all the model annotation?
