### ISSUE TITLE
Datalab test 27.11.2024: Datalab Home page

### ISSUE THREAD

**Issue by mduering** [impresso/impresso-datalab#59]
**Datalab home page**

- [x] Explore and work programmatically with the Impresso Corpus, Data and Models -> Programmatic access to Impresso's Corpus, Data and Models

- [x] #61
- [x] Revised text, ping @e-maud and @simon-clematide: 
Join us in this early stage of development and help us to improve the platform.
The[ Impresso project](https://impresso-project.ch/) strives to create meaningful links across historical media collections. The new Impresso Datalab complements the Web App and offers a platform for programmatic data access and annotation services. It provides access to our data and models via API and a dedicated Python library via Jupyter notebooks. All this with the goal to enable custom analyses of the Impresso corpus and the semantic indexation of external document collections with the help of models created by the project.

**Register**
- [x] Register a new Account to access all features of the Impresso App and Impresso Datalab. [View available Plans](https://dev.impresso-project.ch/datalab/plans) to check which one describes best your situation.
->  
Create your Impresso account to explore the full potential of our Datalab and Web App. Select the User Plan which fits your profile and be ready to provide evidence for Student User, Academic Users and Academic User+ registrations).

- [x] Rename: user plan buttons: Basic User  Student User (coming soon)  Academic User  Academic User+ (coming soon)  
- [x] Username / your username -> User name / Your user name
- [ ]your first name -> Your first name
- [x] your last name -> Your last name
- [x] Verify Password -> Verify password
- [x] I agree to the terms and conditions -> I agree to the Terms of Use
- [x] the "--" looks a bit weird - after having accepted ToU and reopening "Register", see screenshot below
![image](https://github.com/user-attachments/assets/dd0bd20f-8c95-4688-a330-f4f1776fbf38)

- [x] the "Change Colors" button seems a bit out of place to me, I did not notice it initially - perhaps remove "Preview", "User type", "change colours" and add this option in user menu on the top right?
- [x] Verify password: Values of "password" and "verify password" do not match.
-> 
The passwords you entered don't match. Please try again.

- [x] Password must contain at least 8 characters, including uppercase, lowercase, numbers and a punctuation mark.
->
Your password must contain at least 8 characters, including uppercase, lowercase, numbers and a punctuation mark.

- [x] Username: Please enter a valid username that contains at least 8 characters. We accept usernames containing only lowercase letters and numbers, e.g. "johndoe84".
->
Username must be at least 8 characters long, using only lowercase letters and numbers (e.g., johndoe84).

- [x] "Registration almost completed" window
the text below I expected in the purple area:

Download and sign the Non-Disclosure Agreement (NDA), then email it to [info@impresso-project.ch](mailto:info@impresso-project.ch) to complete your registration.

- [x] #65

**Terms of Use**

- [x] You have not accepted the terms of use yet. Please read the entire terms of use document carefully and accept it at the bottom to continue.
-> 
To continue, please review our Terms of Use. Scroll to the bottom of the document and click the checkbox to accept them.

![image](https://github.com/user-attachments/assets/9fb24bba-daeb-4936-8177-9960fe701c9e)

**Getting started**

- [x] Begin exploring Impresso in three simple steps: First login or register your Impresso account, then generate an API key and start running notebooks in your preferred environment (local, Docker, MyBinder, or Google Colab). Launch the tutorial notebook to get started with the Impresso Python library.

**Explore and Visualise your Impresso Data**

- [x] -> Explore and analyse

- [x] Explore and analyse your personal Impresso collections and external datasets in depth with our notebook templates -  beyond the capabilities of the Impresso Web App.

**Annotate your Documents with Impresso Models**

- [x] Enrich your document collections using Impresso models and compare them with our data. Browse our models on HuggingFace to find the right one for your needs.
- [x] #66

**Quick links & Documentation**

- [x] #67
Consult our REST API documentation or the Impresso Python Library guide to interact with the Impresso API.
Find all Impresso models on 🤗 HuggingFace and explore our source code on GitHub.
Visit the Impresso project website to learn more about our work.
Find all Impresso models on 🤗 HuggingFace and explore our source code on GitHub

**Partner links and other links**

- [x] BCUL - wrong link? should be https://www.bcu-lausanne.ch 
- [x] BNF - there seems to be an issue with their EN page, rather use https://www.bnf.fr/fr 
- [x] https://github.com/impresso/impresso-datalab/commit/903ff91 - just to be sure: we really want to show this?
- [x] why the space between plans and terms of use?
![image](https://github.com/user-attachments/assets/aca32a1c-edce-4ac8-93b9-3e0290166f8f)

**Get API token**

- [x] Your Api Token - Impresso Datalab -> Your API Token - Impresso Datalab
- [x] Purple box: API access is always subject to **our** Terms of Use 
- [x] Please login to get your Api Token -> Please login to get your API token

**Browse notebooks**

- [x] Browse our Ipynb Notebooks -> Browse our Notebooks
- [x] #68
- [x] remove "Search" and "Search collections" since now redundant
- [x] remove language tag from icons

**About**

- [x] add links to Terms of Use and User plans in the text:
The Impresso project works with a consortium of partnering libraries and archives on the grounds of legal agreements which respect diverse copyright regulations. The Impresso Terms of Use describe which data is available and how it may be used. Our User Plans reflect variations in access rights for the general public, students and researchers. Note that user plans will evolve in the course of the project and make sure to consult our corpus overview page to understand which data is currently available.

**User plans**

- [x] centre alignment looks a bit odd - left align?

![image](https://github.com/user-attachments/assets/702074b1-ef38-488c-8657-20580b386053)

**Comment by danieleguido** [comment]
I created a new issue for each pending / ready for testing item in this list.
